---
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    bin:
      - bin/*
    lib:
      - lib/**/*.pm
    tests:
      - t/lib/DirBuilder.pm
      - t/find_files.t
      - t/get_files.t
name: diffdir
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - test
  2:
    restart: 1
    edit:
      - bin
      - lib
  3:
    restart: 1
    edit:
      - tests
