---
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    bin:
      - bin/*
    lib:
      - lib/**/*.pm
name: diffdir
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - tests
  2:
    edit:
      - bin
      - lib
